### ISSUE TITLE
How to use Viewer with documents stored in a database

### ISSUE THREAD

**Issue by ManuelHaas** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI#16]
Our Application stores documents as blobs in database.
We do not want so save that blob first to local filesystem to view the document afterwards.
This blob is already be used to download the stored documents to clients. This is done by controller methods that can be called via download links.

So how must the viewer be used to work with blobs or links or streams that provide the document?

**Comment by vladimir-litvinchik** [comment]
@ManuelHaas 

Blob storage is not supported out of the box at the moment. The only storage supported is a [local one](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/tree/master/src/GroupDocs.Viewer.UI.Api.Local.Storage). Anyway, you can use any storage with Viewer. Please check [LocalFileStorage](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/blob/master/src/a.Viewer.UI.Api.Local.Storage/LocalFileStorage.cs) class that implements 
[IFileStorage.cs](
https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/blob/master/src/GroupDocs.Viewer.UI.Core/IFileStorage) interface that declares three methods 
```cs
    public interface IFileStorage
    {
        Task<IEnumerable<FileSystemEntry>> ListDirsAndFilesAsync(string dirPath);

        Task<byte[]> ReadFileAsync(string filePath);

        Task<string> WriteFileAsync(string fileName, byte[] bytes, bool rewrite);
    }
```
Where
* `ListDirsAndFilesAsync` returns the list of files and folders at the specific path in storage.;
*  `ReadFileAsync` returns a byte array of the specific file;
*  `WriteFileAsync` stores a file to storage.

Looking forward to your feedback.

**Comment by ManuelHaas** [comment]
@vladimir-litvinchik Thanks 4 your response.
I'm not sure if I understand it correct. Is the only use case that a user select a file and view it? No way to provide a use case where a user clicks a link and the viewer opens with a loaded file?

**Comment by vladimir-litvinchik** [comment]
@ManuelHaas 

Please check this [sample-viewer-app.zip](https://www.dropbox.com/s/t7tbis7kup2nxu2/sample-viewer-app.zip?dl=1) (89.3 KB). The index page that you’ll see has a link

`<a href="/viewer?file=sample.docx">Click to open sample.docx file</a>`

In case you click the link you’ll be redirected to Viewer UI and sample.docx will be opened automatically.
Please let us know if it works as you expected.

**Comment by ManuelHaas** [comment]
@vladimir-litvinchik thank you for putting me on track.

I integrated your sample code in my .NET Core 6 App. For test purposes, I placed the file sample.docx in the Files subfolder and tried to display it. This leads to an exception in `/viewer-api/loadDocumentDescription` (see stacktrace at the end of the post)

Note: I also used code you provided in your forum because I need to return files that are stored in DB. But I not started modifing your code:

````csharp

services.AddTransient<IFileStorage>(_ =>    new CustomFileStorage(new LocalFileStorage("./Files")));
...

public class CustomFileStorage : IFileStorage
{
    private readonly IFileStorage _fileStorage;

    public SecureFileStorage(IFileStorage fileStorage)
    {
        _fileStorage = fileStorage;
    }

    public Task<IEnumerable<FileSystemEntry>> ListDirsAndFilesAsync(string dirPath)
    {
        return _fileStorage.ListDirsAndFilesAsync(dirPath);
    }

    public async Task<byte[]> ReadFileAsync(string filePath)
    {
        var bytes = await _fileStorage.ReadFileAsync(filePath);
        return bytes;
    }

    public Task<string> WriteFileAsync(string fileName, byte[] bytes, bool rewrite)
    {
        return _fileStorage.WriteFileAsync(fileName, bytes, rewrite);
    }
}
````
````csharp
[14:25:10 ERR] HTTP POST /viewer-api/loadDocumentDescription responded 500 in 5966.8734 ms
System.InvalidOperationException: Property 'JsonResult.SerializerSettings' must be an instance of type 'Newtonsoft.Json.JsonSerializerSettings'.
   at Microsoft.AspNetCore.Mvc.NewtonsoftJson.NewtonsoftJsonResultExecutor.GetSerializerSettings(JsonResult result)
   at Microsoft.AspNetCore.Mvc.NewtonsoftJson.NewtonsoftJsonResultExecutor.ExecuteAsync(ActionContext context, JsonResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
````

What causes the error?

**Comment by vladimir-litvinchik** [comment]
@ManuelHaas 

We're looking into this issue. We'll update you as soon as we have any new information.

**Comment by vladimir-litvinchik** [comment]
@ManuelHaas 

This issue has been fixed. Please update `GroupDocs.Viewer.UI.SelfHost.Api` package to `3.1.13`.
```
<PackageReference Include="GroupDocs.Viewer.UI.SelfHost.Api" Version="3.1.13" />
```

We were using `System.Text.Json` and passed `JsonSerializerOptions` to the `JsonResult` method but with switching to `Microsoft.AspNetCore.Mvc.NewtonsoftJson` the code stopped working because a different options type was expected. The custom action result type has been added to make sure that the global serialization configuration does not affect Viewer's controller.
